services:
  # cloudflare_tunnel:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflare_tunnel
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
  #   networks:
  #     - apex-network

  cloudflare_tunnel-dev:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN_DEV}
    networks:
      - apex-network

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    ports:
     - 443:443
     - 80:80
    volumes:
      - /data/compose/1/services/nginx:/etc/nginx/user_conf.d:ro
      - nginx_secrets:/etc/letsencrypt
      - nginx_cache:/var/lib/nginx/cache
    networks:
      - apex-network

  apex_db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: apex_db
    restart: unless-stopped
    environment:
      - ORACLE_PWD=$APEX_DB_PASS
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
     - 1521:1521
    volumes:
      - apex_data:/opt/oracle/oradata
    networks:
      - apex-network
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -s sys/$APEX_DB_PASS@apex_db:1521/XEPDB1 <<< 'SELECT 1 FROM DUAL;'"]
      interval: 10s
      timeout: 10s
      retries: 5

  apex_ords:
    build:
      context: ./services/apex_ords
      dockerfile: Dockerfile
      args:
        APEX_DB_PASS: ${APEX_DB_PASS}
        APEX_DB_SERVICE: apex_db
    # image: ${APP_NAME}_apex_ords:latest
    container_name: apex_ords
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xms256M -Xmx512M
      # - IGNORE_APEX=TRUE
    ports:
     - 8181:8181
    volumes:
      # - /data/compose/1/services/apex_ords/jetty-compression.xml:/etc/ords/config/global/jetty-compression.xml
      # - /data/compose/1/services/apex_ords/settings.xml:/etc/ords/config/global/settings.xml
      # - /data/compose/1/services/apex_ords/pool.xml:/etc/ords/config/databases/default/pool.xml
      - ords_etc:/etc/ords/config
      - ords_variables:/opt/oracle/variables
    networks:
      - apex-network
    depends_on:
      apex_db:
        condition: service_healthy

  # duplicati:
  #   image: linuxserver/duplicati:version-v2.0.8.1-2.0.8.1_beta_2024-05-07
  #   container_name: duplicati
  #   restart: unless-stopped
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #   ports:
  #     - 8200:8200
  #   volumes:
  #     - ./.backups:/backups
  #     - ./services/duplicati/config:/config
  #     - ./services/duplicati/source:/source
  #     - apex_data:/source/apex_data
  #   networks:
  #     - apex-network

volumes:
  apex_data:
  ords_etc:
  ords_variables:
  nginx_secrets:
  nginx_cache:

networks:
  apex-network:
    driver: bridge
